bin/setup: check for webrick

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -7,4 +7,13 @@ if [ ! -x "$root_path/jsg" ]; then
   echo "jsg not found, installing..."
   git clone https://github.com/jch/jsg.git "$root_path/jsg"
   echo "Create a GitHub personal access token with no permissions to increase markdown API rate limit"
+  echo
 fi
+
+if ! ruby -rwebrick -e '' 2>/dev/null; then
+  echo "webrick not found, installing..."
+  gem install 'webrick'
+  echo
+fi
+
+echo "bin/dev to start a local server"
